spring.application.name=denguesense
server.port=8080

#-----------------------------------------------------------------------------------------------------------------
# LOG
#-----------------------------------------------------------------------------------------------------------------

logging.file.name=/opt/tomcat/logs/Denguesense-Backend.log
logging.logback.rollingpolicy.file-name-pattern=${logging.file.name}.%d{yyyy-MM-dd}.%i.gz
logging.logback.rollingpolicy.max-history=365
logging.logback.rollingpolicy.max-file-size=50MB
#logging.pattern.console=

spring.profiles.active=local

logging.level.org.apache.http=INFO
logging.level.httpclient.wire=INFO

# Backend Base URL for OAuth Callbacks
Denguesense.backend.base.url=http://localhost:8080
