spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references = true

spring.mail.host=${SES_SMTP}
spring.mail.port=2525
spring.mail.username=${SES_USERNAME}
spring.mail.password=${SES_PASSWORD}
denguesense.from.email=${FROM_EMAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

denguesense.frontend.base.url=${FRONTEND_URL}

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
firebase.credentials-file=${FIREBASE_CREDENTIALS_FILE:}

spring.security.oauth2.client.registration.google.client-id=${AUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${AUTH2_SECRET}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Backend Base URL for OAuth Callbacks
#pawura.backend.base.url=${BACKEND_URL:}https://api.pawura.lk
